"""AES-256-GCM helpers for secrets that must not sit in plaintext at rest.

The only secret persisted through here is the Instagram session, whose
`sessionid` cookie is equivalent to full control of the official account —
i.e. read and send DMs for every user. On Render's free tier the disk is
ephemeral, so without this every container start would do a fresh
`client.login()` from a new egress IP, which is the pattern that earns an
Instagram checkpoint or ban.

This module must never log plaintext.
"""

from __future__ import annotations

import base64
import binascii
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_NONCE_BYTES = 12  # GCM's standard nonce length
_KEY_BYTES = 32  # AES-256


class KeyError_(ValueError):
    """Raised when `IG_SESSION_KEY` is missing or malformed."""


def load_key(encoded: str) -> bytes:
    """Decode a configured key to 32 bytes.

    Accepts 64 hex characters or base64. The key is used directly rather than
    stretched through a KDF: it is generated by `openssl rand`, not chosen by a
    human, so it already has full entropy and a KDF would only add a second place
    to misconfigure things.
    """
    raw = (encoded or "").strip()
    if not raw:
        raise KeyError_("IG_SESSION_KEY is not set")
    if len(raw) == _KEY_BYTES * 2:
        try:
            return binascii.unhexlify(raw)
        except binascii.Error as exc:
            raise KeyError_(f"IG_SESSION_KEY is not valid hex: {exc}") from None
    try:
        key = base64.b64decode(raw, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise KeyError_(f"IG_SESSION_KEY is neither hex nor base64: {exc}") from None
    if len(key) != _KEY_BYTES:
        raise KeyError_(
            f"IG_SESSION_KEY must decode to {_KEY_BYTES} bytes, got {len(key)}"
        )
    return key


def encrypt(key: bytes, plaintext: bytes, *, aad: bytes = b"") -> bytes:
    """Return `nonce || ciphertext+tag`."""
    nonce = os.urandom(_NONCE_BYTES)
    return nonce + AESGCM(key).encrypt(nonce, plaintext, aad or None)


def decrypt(key: bytes, blob: bytes, *, aad: bytes = b"") -> bytes:
    """Reverse `encrypt`. Raises `InvalidTag` if the key or blob is wrong.

    An `InvalidTag` is indistinguishable from a corrupt blob on purpose — do not
    leak which, and never log either.
    """
    if len(blob) < _NONCE_BYTES + 16:
        raise InvalidTag("ciphertext too short")
    nonce, body = blob[:_NONCE_BYTES], blob[_NONCE_BYTES:]
    return AESGCM(key).decrypt(nonce, body, aad or None)